footer_settings:
  footer_top_content:
    value: "<p><a href=\"#\">Hae yhteystietoja ja numeroita</a>&nbsp;</p>\r\n\r\n<p><a class=\"hds-button hds-button--secondary\" href=\"#\"><span class=\"hds-button__label\">Helsinki-info 09 310 1691</span></a></p>\r\n"
  footer_top_title: Yhteystiedot
