name: strategiantietopohja
recipe: drupal8
config:
  webroot: public
  via: nginx
  php: '7.4'

proxy:
  redis:
    - redis.kirami.site

services:
  appserver:
    xdebug: true
    config:
      php: .lando.php.ini
    overrides:
      environment:
        # support debugging Drush with XDEBUG.
        # This should work.
        ENVIRONMENT: "local"
        PHP_IDE_CONFIG: "serverName=appserver"
  elasticsearch:
    type: elasticsearch:5.6.15
  redis:
    type: redis
    mem: 128

tooling:
  drush:
    service: appserver
    cmd: drush --root=/app/web
