<?php

/**
 * @file
 * Contains helstra_article.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function helstra_article_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the helstra_article module.
    case 'help.page.helstra_article':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides customizations for articles') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function helstra_article_theme() {
  return [
    'article_index_block' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
  ];
}
